apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # -----------------------------
      # Node exporter
      # -----------------------------
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

      # -----------------------------
      # Kube-state-metrics
      # -----------------------------
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']

      # -----------------------------
      # Prometheus itself
      # -----------------------------
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor.monitoring.svc.cluster.local:8080']
