apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-media-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data/backend-media
    type: DirectoryOrCreate
