name: CD - Docker + Minikube

on:
  pull_request:
    branches: ["main"]
    types: [closed]

env:
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/freelance-backend:${IMAGE_TAG} backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/freelance-backend:${IMAGE_TAG}

      - name: Build & push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/freelance-frontend:${IMAGE_TAG} frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/freelance-frontend:${IMAGE_TAG}

  deploy:
    runs-on: self-hosted
    needs: docker
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v4

      - name: Apply manifests
        run: kubectl apply -R -f k8s/

      - name: Update backend image
        run: |
          kubectl set image deployment/django-backend \
            django-backend=${{ secrets.DOCKERHUB_USERNAME }}/freelance-backend:${IMAGE_TAG} \
            -n freelance

      - name: Update frontend image
        run: |
          kubectl set image deployment/frontend \
            frontend=${{ secrets.DOCKERHUB_USERNAME }}/freelance-frontend:${IMAGE_TAG} \
            -n freelance

      - name: Rollout status
        run: |
          kubectl rollout status deployment/django-backend -n freelance
          kubectl rollout status deployment/frontend -n freelance

      - name: Verify
        run: kubectl get pods,svc -n freelance
